# Generated by Django 3.0.5 on 2020-07-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocker',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('contact', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
